pwebsite/notes/urls.py
from django.conf.urls import patterns, include, url

import views

urlpatterns = patterns('',
    url(r'^$', views.notes),
    url(r'^(?P<post_id>\d+)/$', views.post),
    url(r'^search/(?P<username>\w{0,50})/$', views.user_posts),
    url(r'^search/(?P<day>\d{2})-(?P<month>\d{2})-(?P<year>\d{4})/$', views.date_posts),
)

pwebsite/transfers/urls.py
from django.conf.urls import patterns, include, url

import views

urlpatterns = patterns('',
    url(r'^$', views.home),
    url(r'^sumo/$', views.sumo),
    url(r'^itk-ro/$', views.itk_ro),
    url(r'^info-screen/$', views.info_screen),
    )

pwebsite/transfers/models.py
from django.db import models

class Transfer_Post(models.Model):
	poster = models.CharField(max_length=100)
	poster_url = models.CharField(max_length=500)
	context_url = models.CharField(max_length=500, null=True, blank=True)
	context_post = models.TextField(null=True, blank=True)
	context_poster = models.CharField(max_length=100, null=True, blank=True)
	post_content = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True, editable=False, null=True, blank=True)

	class Meta:
		verbose_name="Transfer post"
		verbose_name_plural = 'Transfers posts'

class SC_Rating(models.Model):
	rating_type = models.CharField(max_length=100)
	number_of = models.IntegerField()
	post = models.ForeignKey(Transfer_Post)

	class Meta:
		verbose_name="Rating"
		verbose_name_plural = 'Ratings'


class RO_Post(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField()

	class Meta:
		verbose_name="RO post"
		verbose_name_plural = 'RO posts'

pwebsite/transfers/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from transfers.models import SC_Rating, Transfer_Post, RO_Post
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

import json
from django.core import serializers
from django.http import HttpResponse

##################
##### Views ######
##################

# from django.views.decorators.csrf import csrf_exempt # Remove
@csrf_exempt # Remove
@login_required
def home(request):

	posts = Transfer_Post.objects.all()
	posts_to_be_displayed = 30

	if request.method == 'POST':

		data = get_new_articles(posts, posts_to_be_displayed, request)

		return HttpResponse(data, content_type="application/json")

	else:
		posts = posts.order_by('-id')[:posts_to_be_displayed]
		ratings = SC_Rating.objects.filter(post__in=posts)
		return render_to_response('transfers_home.html', {'posts':posts, 'ratings':ratings}, context_instance=RequestContext(request))

# Sumo view
@login_required
def sumo(request):
	posts = Transfer_Post.objects.all()
	ratings = SC_Rating.objects.all()
	return render_to_response('transfers_sumo.html', {'posts':posts, 'ratings':ratings}, context_instance=RequestContext(request))

# ITK RO section
@login_required
def itk_ro(request):
	ro_posts = RO_Post.objects.all().order_by('-id')
	if request.method == 'POST':
		data = get_new_ro_posts(ro_posts, request)
		return HttpResponse(data, content_type="application/json")
	else:
		return render_to_response('transfers_itk_ro.html', {'ro_posts':ro_posts}, context_instance=RequestContext(request))


@login_required
def info_screen(request):
	posts = Transfer_Post.objects.all()
	posts_to_be_displayed = 30

	if request.method == 'POST':

		data = get_new_articles(posts, posts_to_be_displayed, request)

		return HttpResponse(data, content_type="application/json")

	else:
		posts = posts.order_by('-id')[:posts_to_be_displayed]
		ratings = SC_Rating.objects.filter(post__in=posts)
		ro_posts = RO_Post.objects.all().order_by('-id')
		return render_to_response('transfers_infoscreen.html', {'posts':posts, 'ratings':ratings, 'ro_posts':ro_posts}, context_instance=RequestContext(request))





#############################
##### Helper functions ######
#############################
from django.core.serializers.json import DjangoJSONEncoder
def get_new_articles(posts, posts_to_be_displayed, request):
	# Get list of posts currently beeing displayed and convert to int
		post_ids = request.POST.getlist('post_ids[]')
		post_ids = map(int, post_ids)

		# If func == update_posts
		# Remove posts allready displayed, and old posts not to be displayed (Fix)

		if post_ids:
			for post in posts:
				if ( post.id < min(post_ids) ) or ( post.id in post_ids ):
					posts = posts.exclude(id=post.id)

		# Get corresponding ratings
		ratings = SC_Rating.objects.filter(post__in=posts)

		# Serialize / Convert to JSON
		posts_json = serializers.serialize('python',posts)
		ratings_json = serializers.serialize('python', ratings)

		data =  json.dumps( {'posts':posts_json, 'ratings':ratings_json}, cls=DjangoJSONEncoder )

		return data

def get_new_ro_posts(ro_posts, request):
	post_ids = request.POST.getlist('post_ids[]')
	post_ids = map(int, post_ids)

	for ro_post in ro_posts:
		if ro_post.id in post_ids:
			ro_posts = ro_posts.exclude(id=ro_post.id)

	ro_posts_json = serializers.serialize('python',ro_posts)

	data = json.dumps( {'ro_posts':ro_posts_json}, cls=DjangoJSONEncoder )

	return data

pwebsite/templates/transfers/get_posts.html
<script>
	var months = new Array(12);
	months[0] = "Jan";
	months[1] = "Feb";
	months[2] = "Mar";
	months[3] = "Apr";
	months[4] = "May";
	months[5] = "Jun";
	months[6] = "Jul";
	months[7] = "Aug";
	months[8] = "Sep";
	months[9] = "Oct";
	months[10] = "Nov";
	months[11] = "Dec";
	$(document).ready(function(){
		setInterval(function(){

			var displayedPosts = [];
			$("#posts").find("article").each(function(){ displayedPosts.push(this.id); });

			$.ajax({
				type : "POST",
				url : "/transfers/",
				dataType : 'json',
				data : {
					post_ids : displayedPosts,
					csrfmiddlewaretoken: '{{ csrf_token }}'
				},

				success: function(result){

			// Iterate each post
			$.each(result.posts, function(x, post) {
				var article = "";
				article += '<article id="' + post.pk + '" style="border-color:#46b8da;">' + '<a href="' + post.fields.poster_url + '">'+ post.fields.poster + '</a>';

				var d = new Date(post.fields.created_date);
				var date = d.getHours() + ':' + d.getMinutes() + ', ' + d.getDate() + " " + months[d.getMonth()] + " " + d.getFullYear() ;
				
				article += '<small class="pull-right">' + date + '</small>';
				article += '<br>';
				article += '<br>';
				if(post.fields.context_post.trim()){
					article += '<div class="panel panel-default">';
					article += '<div class="panel-heading">' + post.fields.context_poster + ' said:  <a href="' + post.fields.context_url + '">↑</a></div>';
					article += '<div class="panel-body">';
					article += post.fields.context_post;
					article += '</div>';
					article += '</div>';
				}
				article += post.fields.post_content;
				article += '<hr>';

				$.each(result.ratings, function(y, rating) {
					if(post.pk == rating.fields.post){
						article += rating.fields.rating_type + ":" + rating.fields.number_of + " ";
						// DELETE FROM LIST
					}
				});

				article += "</article>";

				// twitter effect
				$(article).hide().prependTo('#posts').slideDown('slow');

				//Fade test
				setTimeout(function()
				{
					var div = $('#'+post.pk);
					$({alpha:1}).animate({alpha:0}, 
					{
						duration: 1000,

						step: function(){
							div.removeAttr("style");
						}
					});

				}, 5000);
			});
},
});





},30000);
});	
</script>

pwebsite/templates/transfers/get_ro_posts.html
<script>
	$(document).ready(function(){
		setInterval(function(){

			var displayedPosts = [];
			$("#ro").find("article").each(function(){ displayedPosts.push(this.id); });

			$.ajax({
				type : "POST",
				url : "/transfers/itk-ro/",
				dataType : 'json',
				data : {
					post_ids : displayedPosts,
					csrfmiddlewaretoken: '{{ csrf_token }}'
				},

				success: function(result){
					

			// Iterate each post
			$.each(result.ro_posts, function(x, ro_post) {
				var article = "";
				article += '<article id="' + ro_post.pk + '" style="border-color:#46b8da;">';
				article += '<h5>' + ro_post.fields.title + '</h5>';
				article += ro_post.fields.content;
				article += "</article>";

				// twitter effect
				$(article).hide().prependTo('#ro').slideDown('slow');

				//Fade test
				setTimeout(function()
				{
					var div = $('#'+ro_post.pk);
					$({alpha:1}).animate({alpha:0}, 
					{
						duration: 1000,

						step: function(){
							div.removeAttr("style");
						}
					});

				}, 5000);
			});
		},
	});





		},30000);
	});	
</script>

pwebsite/templates/transfers/transfers_base.html
<html>
<head>
	<title>Transfers</title>

	<meta charset="utf-8">

	<link href="/static/css/transfers/css/bootstrap.css" rel="stylesheet">
	<link href="/static/css/transfers/css/style.css" rel="stylesheet">

	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

</head>

<body>

	<div id="wrapper" class="">

		<!-- Sidebar -->
		<div id="sidebar-wrapper">
			<ul id="sidebar_menu" class="sidebar-nav">
				<li class="sidebar-brand"><a id="menu-toggle" href="#">Menu<span id="main_icon" class="glyphicon glyphicon-align-justify"></span></a></li>
			</ul>
			<ul class="sidebar-nav" id="sidebar">
				<li><a href="/transfers/">Home<span class="sub_icon glyphicon glyphicon-home"></span></a></li>
				<!-- <li><a href="/transfers/sumo/">Sumo<span class="sub_icon glyphicon glyphicon-facetime-video"></span></a></li> -->
				<li><a href="/transfers/itk-ro/">ITK RO<span class="sub_icon glyphicon glyphicon-comment"></span></a></li>
				<li><a href="/transfers/info-screen/">Full<span class="sub_icon glyphicon glyphicon glyphicon-th-large"></span></a></li>
			</ul>
			<!-- <ul class="sidebar-bottom" style="margin-bottom: 0px; padding-bottom: 0px;">
				<li><a href="/transfers/info/">Info<span class="sub_icon glyphicon glyphicon glyphicon-th-large"></span></a></li>
			</ul> -->
		</div>
		<!-- /Sidebar -->

		<!-- Page content -->
		<div id="page-content-wrapper">
			<!-- Keep all page content within the page-content inset div! -->
			<div class="page-content inset">

				<div class="row" style="padding-top: 20px;">
				<div class="col-md-12" id="posts" style="padding-left: 40px;">
						<div class="alert alert-info" role="alert">
							<strong>Warning!</strong> The transfer window is closed, and this website will not be updated until the next window opens.
						</div>
					</div>
				</div>
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>

	<script>
		$("#menu-toggle").click(function(e) {
			e.preventDefault();
			$("#wrapper").toggleClass("active");
		});
	</script>
	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-53796474-1', 'auto');
		ga('send', 'pageview');

	</script>

</body>
</html>

pwebsite/templates/transfers/transfers_home.html
{% extends "transfers_base.html" %}
{% block content %}
<div class="row" style="padding-top: 20px;">
	<div class="col-md-7" id="posts" style="padding-left: 40px;">

		{% for post in posts %}
		<article id="{{post.id}}">
			<a href="{{post.poster_url}}">{{ post.poster }}</a> <small class="pull-right">{{post.created_date|date:"H:i, d M Y"}}</small> <br><br>

			{% if post.context_post %}

			<div class="panel panel-default">
				<div class="panel-heading">{{post.context_poster}} said:  <a href="{{post.context_url}}">↑</a></div>
				<div class="panel-body">
					{{ post.context_post|safe }}
				</div>
			</div>
			
			{% endif %}

			{{ post.post_content|safe }}

			<hr>

			<table class="ratings">
				{% for rating in post.sc_rating_set.all %}
				<tr id="{{ rating.rating_type }}">
					<td>{{ rating.rating_type }} :</td>
					<td>{{ rating.number_of }}</td>
				</tr>
				{% endfor %}
			</table>
		</article>
		{% endfor %}

	</div>

	<div class="col-md-4">
		{% include 'twitter-feed.html' %}
	</div>

</div>

{% include 'get_posts.html' %}



{% endblock %}

pwebsite/templates/transfers/transfers_infoscreen.html
{% extends "transfers_base.html" %}
{% block content %}
<div class="row" style="padding-top: 20px;">
	<div class="col-md-4" style="padding-left: 40px;">
		
		<p class="lead">Daily ITK thread</p>
		<div id="posts">
			{% for post in posts %}
			<article id="{{post.id}}">
				<a href="{{post.poster_url}}">{{ post.poster }}</a> <small class="pull-right">{{post.created_date|date:"H:i, d M Y"}}</small> <br><br>

				{% if post.context_post %}

				<div class="panel panel-default">
					<div class="panel-heading">{{post.context_poster}} said:  <a href="{{post.context_url}}">↑</a></div>
					<div class="panel-body">
						{{ post.context_post|safe }}
					</div>
				</div>
				
				{% endif %}

				{{ post.post_content|safe }}

				<hr>

				<table class="ratings">
					{% for rating in post.sc_rating_set.all %}
					<tr id="{{ rating.rating_type }}">
						<td>{{ rating.rating_type }} :</td>
						<td>{{ rating.number_of }}</td>
					</tr>
					{% endfor %}
				</table>
			</article>
			{% endfor %}
		</div>

	</div>
	<!-- ZOOOOMG TEST-->
	<div class="col-md-4">
		<p class="lead">ITK</p>
		<div id="ro">
			{% for ro_post in ro_posts %}
			<article id={{ro_post.id}}>
				<h5>{{ro_post.title}}</h5>
				{{ ro_post.content|safe }}
			</article>
			{% endfor %}
		</div>
	</div>
	<!-- END END NED -->
	<div class="col-md-3">
		<p class="lead">Twitter</p>
		{% include 'twitter-feed.html' %}
	</div>

</div>

{% include 'get_posts.html' %}
{% include 'get_ro_posts.html' %}


{% endblock %}

pwebsite/templates/transfers/transfers_itk_ro.html
{% extends "transfers_base.html" %}
{% block content %}

<div class="row" style="padding-top: 20px;">
	<div class="col-md-7" style="padding-left: 40px;">
		<p class="lead">ITK from Spurs Community RO-section</p>
		<div id="ro">
			{% for ro_post in ro_posts %}
			<article id={{ro_post.id}}>
				<h5>{{ro_post.title}}</h5>
				{{ ro_post.content|safe }}
			</article>
			{% endfor %}
		</div>
	</div>
	<div class="col-md-4">
		{% include 'twitter-feed.html' %}
	</div>
</div>
{% include 'get_ro_posts.html' %}

{% endblock %}

pwebsite/templates/transfers/transfers_sumo.html
{% extends "transfers_base.html" %}
{% block content %}

<div class="row">
	<div class="col-md-11" style="padding-left: 40px;">
		<!-- <iframe height="470" width="80%" frameBorder="0" align="center" style="position: relative; top: -65px;" src="http://sumo.tv2.no/direkte-tv/sportskanalen/tv-2-sportskanalen-115210.html">your browser does not support IFRAMEs</iframe> -->
		<iframe height="100%" width="100%" frameBorder="0" align="center" style="position: relative; top: -65px;" src="http://sumo.tv2.no/direkte-tv/sportskanalen/tv-2-sportskanalen-115210.html">your browser does not support IFRAMEs</iframe>

	</div>
</div>

{% endblock %}

pwebsite/templates/transfers/twitter-feed.html
<div class="twitter-feed">
<a class="twitter-timeline" height="100%" href="https://twitter.com/andreasroyrvik0/lists/transfers" data-widget-id="494887251940106240">Tweets from https://twitter.com/andreasroyrvik0/lists/transfers</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>